# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Rpi-Timelapse-Camera
version: "1.0"
slug: timelapse_camera
description: Timelapse Addon for HAOS on Rpi with Rpi-Camera Module
url: "https://github.com/Tobiwan91/Rpi-Timelapse-Camera/tree/main/timelapse_camera"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
